on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  webapp-lint:
    name: Lint and TS check webapp
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dragenet/ts-next-app-dir-template/.github/actions/setup-project@actions/setup-project/v0.1.3-berry

      - name: Type check
        run: yarn web tscheck

      - name: Lint
        run: yarn web lint

  e2e-lint:
    name: Lint and TS check e2e
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dragenet/ts-next-app-dir-template/.github/actions/setup-project@actions/setup-project/v0.1.3-berry

      - name: Type check
        run: yarn e2e tscheck

      - name: Lint
        run: yarn e2e lint

  webapp-unit:
    name: Webapp unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dragenet/ts-next-app-dir-template/.github/actions/setup-project@actions/setup-project/v0.1.3-berry

      - name: Run tests with jest
        run: yarn web test:ci

  webapp-e2e:
    name: Webapp e2e test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dragenet/ts-next-app-dir-template/.github/actions/setup-project@actions/setup-project/v0.1.3-berry

      - name: Build Next.js app
        run: yarn web build

      - name: Cypress.io
        uses: cypress-io/github-action@v5
        with:
          start: yarn web start
          wait-on: 'http://localhost:3000'
          browser: chrome
          project: ./packages/e2e